<script src="<?php echo base_url() ?>resources/frontend/js/jquery.min.js"></script> 
<script src="<?php echo base_url() ?>resources/frontend/js/bootstrap.min.js"></script> 
<script src="<?php echo base_url() ?>resources/frontend/js/twitter-bootstrap-hover-dropdown.min.js"></script> 
<script src="<?php echo base_url() ?>resources/frontend/js/retina.js"></script> 
<script src="<?php echo base_url() ?>resources/frontend/js/jquery.slickforms.js"></script> 
<script src="<?php echo base_url() ?>resources/frontend/js/jquery.animsition.min.js"></script> 
<script src="<?php echo base_url() ?>resources/frontend/js/isotope.pkgd.min.js"></script> 
<script src="<?php echo base_url() ?>resources/frontend/js/owl.carousel.min.js"></script> 
<script src="<?php echo base_url() ?>resources/frontend/js/instafeed.min.js"></script> 
<script src="<?php echo base_url() ?>resources/frontend/js/jquery.easytabs.min.js"></script> 
<script src="<?php echo base_url() ?>resources/frontend/js/google-code-prettify/prettify.js"></script> 
<script src="<?php echo base_url() ?>resources/frontend/js/fotorama.js"></script> 
<script src="<?php echo base_url() ?>resources/frontend/js/jquery.dcflickr.1.0.js"></script> 
<script src="<?php echo base_url() ?>resources/frontend/js/idangerous.swiper.min.js"></script> 
<script src="<?php echo base_url() ?>resources/frontend/js/jquery.fancybox.pack.js"></script> 
<script src="<?php echo base_url() ?>resources/frontend/js/fancybox/helpers/jquery.fancybox-thumbs.js?v=1.0.2"></script> 
<script src="<?php echo base_url() ?>resources/frontend/js/fancybox/helpers/jquery.fancybox-media.js?v=1.0.0"></script> 
<script src="<?php echo base_url() ?>resources/frontend/js/jquery.fitvids.js"></script> 
<script src="<?php echo base_url() ?>resources/frontend/js/jquery.themepunch.revolution.min.js"></script> 
<script src="<?php echo base_url() ?>resources/frontend/js/jquery.themepunch.tools.min.js"></script> 
<script src="<?php echo base_url() ?>resources/frontend/js/jquery.divas-1.0.min.js"></script> 
<script src="<?php echo base_url() ?>resources/frontend/js/imagesloaded.pkgd.min.js"></script> 
<script src="<?php echo base_url() ?>resources/frontend/js/scripts.js"></script>